import type { Session } from "@flight-recorder/sdk";

const t = (base: number, offsetMs: number) => base + offsetMs;

function makeSession(idSuffix: string, labelText: string, baseOffset: number): Session {
  const BASE = Date.now() - baseOffset;
  const sid = `demo-${idSuffix}`;
  return {
    id: sid,
    label: labelText,
    tags: ["demo"],
    status: "ended",
    startedAt: BASE,
    endedAt: BASE + 9200,
    events: [
      {
        id: `${sid}-e1`,
        sessionId: sid,
        type: "session-started",
        timestamp: BASE,
        label: labelText,
        tags: ["demo"],
      },
      {
        id: `${sid}-e2`,
        sessionId: sid,
        type: "prompt",
        timestamp: t(BASE, 80),
        model: "gpt-4o",
        prompt: "What is the capital of France? Please be concise.",
        systemPrompt: "You are a helpful assistant.",
        temperature: 0.7,
        maxTokens: 256,
      },
      {
        id: `${sid}-e3`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 310),
        token: "Paris",
        index: 0,
      },
      {
        id: `${sid}-e4`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 360),
        token: " is",
        index: 1,
      },
      {
        id: `${sid}-e5`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 410),
        token: " the",
        index: 2,
      },
      {
        id: `${sid}-e6`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 460),
        token: " capital",
        index: 3,
      },
      {
        id: `${sid}-e7`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 510),
        token: " of",
        index: 4,
      },
      {
        id: `${sid}-e8`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 560),
        token: " France.",
        index: 5,
        isFinal: true,
      },
      {
        id: `${sid}-e9`,
        sessionId: sid,
        type: "completion",
        timestamp: t(BASE, 700),
        response: "Paris is the capital of France.",
        finishReason: "stop",
        promptTokens: 22,
        completionTokens: 8,
        totalTokens: 30,
        estimatedCost: 0.00018,
      },
      {
        id: `${sid}-e10`,
        sessionId: sid,
        type: "prompt",
        timestamp: t(BASE, 1400),
        model: "gpt-4o",
        prompt:
          "Can you search for the latest facts about the Eiffel Tower and give me a brief summary?",
        temperature: 0.7,
        maxTokens: 512,
      },
      {
        id: `${sid}-e11`,
        sessionId: sid,
        type: "tool-call",
        timestamp: t(BASE, 1680),
        toolName: "web_search",
        toolCallId: `${sid}-call-1`,
        input: { query: "Eiffel Tower history facts 2024" },
      },
      {
        id: `${sid}-e12`,
        sessionId: sid,
        type: "tool-result",
        timestamp: t(BASE, 3100),
        toolCallId: `${sid}-call-1`,
        output: {
          results: [
            "The Eiffel Tower was built between 1887–1889 for the 1889 World's Fair.",
            "Height: 330 meters (1,083 ft) including antenna.",
            "Named after engineer Gustave Eiffel.",
            "Receives approximately 7 million visitors per year.",
          ],
        },
        success: true,
        durationMs: 1420,
      },
      {
        id: `${sid}-e13`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 3500),
        token: "The",
        index: 0,
      },
      {
        id: `${sid}-e14`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 3550),
        token: " Eiffel",
        index: 1,
      },
      {
        id: `${sid}-e15`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 3600),
        token: " Tower",
        index: 2,
      },
      {
        id: `${sid}-e16`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 3650),
        token: " is",
        index: 3,
      },
      {
        id: `${sid}-e17`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 3700),
        token: " a",
        index: 4,
      },
      {
        id: `${sid}-e18`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 3750),
        token: " wrought-iron",
        index: 5,
      },
      {
        id: `${sid}-e19`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 3800),
        token: " lattice",
        index: 6,
      },
      {
        id: `${sid}-e20`,
        sessionId: sid,
        type: "token",
        timestamp: t(BASE, 3850),
        token: " tower",
        index: 7,
        isFinal: true,
      },
      {
        id: `${sid}-e21`,
        sessionId: sid,
        type: "completion",
        timestamp: t(BASE, 8800),
        response:
          "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris. Built between 1887–1889 as the centerpiece of the 1889 World's Fair, it stands 330 meters tall and welcomes around 7 million visitors annually.",
        finishReason: "stop",
        promptTokens: 185,
        completionTokens: 52,
        totalTokens: 237,
        estimatedCost: 0.001422,
      },
      {
        id: `${sid}-e22`,
        sessionId: sid,
        type: "session-ended",
        timestamp: t(BASE, 9200),
        durationMs: 9200,
        totalEvents: 22,
        totalTokens: 267,
        estimatedCost: 0.001602,
      },
    ],
  } satisfies Session;
}

export const demoSessions: Session[] = [
  makeSession("1", "Chat · GPT-4o · Paris Q&A", 120_000),
  makeSession("2", "Chat · GPT-4o · Tool Call Demo", 60_000),
];
